"""PR 写作 Agent：汇总前面各 Agent 结论，生成可提交的 PR 草稿。"""

from __future__ import annotations

from agent.base_agent import BaseAgent
from app.config import llm_configured


class PRWriterAgent(BaseAgent):
    name = "pr_writer"

    def run(self, state: dict) -> dict:
        repo_name = self.repo_name
        analysis = state.get("analysis", {}) or {}
        bugs = state.get("bugs", []) or []
        optimizations = state.get("optimizations", []) or []
        docs = state.get("docs", "") or ""
        tests = state.get("tests", "") or ""

        bug_lines = "\n".join(
            f"- [ ] {b.get('severity', 'low')}: {b.get('file', '')}:{b.get('line', '')} {b.get('message', '')}"
            for b in bugs[:15]
        ) or "- 暂未发现明确缺陷"
        opt_lines = "\n".join(
            f"- [ ] {o.get('file', '')}: {o.get('message', '')}" for o in optimizations[:15]
        ) or "- 暂未给出优化建议"

        title = f"chore: DevAgent-Workspace 自动分析 {repo_name}"
        body = (
            f"## 变更说明\n"
            f"本 PR 由 DevAgent-Workspace 多 Agent 流水线基于仓库 {repo_name} 自动生成，"
            f"包含缺陷清单、优化建议、测试骨架与文档补全草稿。\n\n"
            f"## 分析概览\n"
            f"- 文本文件数: {analysis.get('text_file_count', '?')}\n"
            f"- 框架线索: {', '.join(analysis.get('framework_hints', []) or ['未识别'])}\n\n"
            f"## 待处理问题（Checklist）\n{bug_lines}\n\n"
            f"## 优化建议（Checklist）\n{opt_lines}\n\n"
            f"## 文档/测试\n"
            f"- 测试骨架: {'已生成' if tests else '无'}\n"
            f"- README 草稿: {'已生成' if docs else '无'}\n\n"
            f"---\nGenerated by DevAgent-Workspace"
        )

        llm_body = ""
        if llm_configured():
            llm_body = self.call_llm(
                system_prompt="你是资深开源维护者，请把仓库分析结论整理成一篇专业、简洁的 GitHub PR 描述（Markdown，中文）。",
                user_prompt=f"仓库: {repo_name}\n分析:\n{body}",
            ) or ""

        pr = {"title": title, "body": body, "llm_body": llm_body}
        return {
            "pr": pr,
            "logs": [f"[pr_writer] 生成 PR 草稿: {title}"],
        }
